### ISSUE TITLE
[New Map] Shows white screen.

### ISSUE THREAD

**Issue by capoaira** [2Abendsegler/GClh#1595]
**Describe the bug**
https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/page/5/&tab=comments#comment-5875028 and the following Post

**Desktop (please complete the following information):**
 - OS: 
 - Browser: chome

**Additional context**
Info aus der Konsole: 
Hier der Text aus der Console:

```
react-dom.production.min.js:125 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at Dh (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:133:303)
at Aj (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:158:298)
at unstable_runWithPriority (https://unpkg.com/react@16.13.1/umd/react.production.min.js:25:260)
at Da (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:60:280)
at ab (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:154:190)
at Te (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:146:355)
at https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:61:68
at unstable_runWithPriority (https://unpkg.com/react@16.13.1/umd/react.production.min.js:25:260)
at Da (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:60:280)
at Pg (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:61:14)
Me @ react-dom.production.min.js:125
react.production.min.js:24 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
at Dh (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:133:303)
at Aj (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:158:298)
at unstable_runWithPriority (https://unpkg.com/react@16.13.1/umd/react.production.min.js:25:260)
at Da (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:60:280)
at ab (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:154:190)
at Te (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:146:355)
at https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:61:68
at unstable_runWithPriority (https://unpkg.com/react@16.13.1/umd/react.production.min.js:25:260)
at Da (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:60:280)
at Pg (https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js:61:14)
userscript.html?name=GC%20little%20helper%20II.user.js&id=c652b406-d4ab-405e-805a-92fdc4933dde:10861 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
at MutationObserver.cb_sidebar (userscript.html?name=GC%20little%20helper%20II.user.js&id=c652b406-d4ab-405e-805a-92fdc4933dde:10861)
```

Ich schließe daraus, dass wir irgendein Element entfernen, welches für das GS-Skript `https://unpkg.com/react-dom@16.13.1/umd/react-dom.production.min.js` wichtig ist. Ich kann den Fehler allerdings nicht nachvollziehen.
Alle anderen Tampermonkey Skripte oder andere Add-Ons sind laut mr.checkmate ausgestellt.

@2Abendsegler, @Ruko2010 habt ihr eine Idee, wie dieser Bug zustande kommt bzw. könnt ihr ihn reproduzieren?

**Comment by 2Abendsegler** [comment]
@capoaira 
Ich habe alles mögliche ausprobiert, kann das aber auch nicht nachstellen. 

Ich vermute dass es sich um eine Einstellung im Config handelt. Vielleicht kann jemand der das Problem nachstellen kann seine Config Datei downloaden und uns zusenden. Vorher sollte er die Home Koordinaten im Config ändern. Anschließend können wir dann mit dessen Einstellungen testen. 

Mehr fällt mir jetzt nicht ein.

**Comment by capoaira** [comment]
mr.checkmate hat mir folgende config geschickt (homecoords und friends entfernt):

```json
{
  "settings_custom_bookmark[0]": "#",
  "settings_bookmarks_title[36]": "Custom0",
  "settings_custom_bookmark_target[0]": "",
  "settings_custom_bookmark[1]": "#",
  "settings_bookmarks_title[37]": "Custom1",
  "settings_custom_bookmark_target[1]": "",
  "settings_custom_bookmark[2]": "#",
  "settings_bookmarks_title[38]": "Custom2",
  "settings_custom_bookmark_target[2]": "",
  "settings_custom_bookmark[3]": "#",
  "settings_bookmarks_title[39]": "Custom3",
  "settings_custom_bookmark_target[3]": "",
  "settings_custom_bookmark[4]": "#",
  "settings_bookmarks_title[40]": "Custom4",
  "settings_custom_bookmark_target[4]": "",
  "settings_custom_bookmark[5]": "#",
  "settings_bookmarks_title[41]": "Custom5",
  "settings_custom_bookmark_target[5]": "",
  "settings_custom_bookmark[6]": "#",
  "settings_bookmarks_title[42]": "Custom6",
  "settings_custom_bookmark_target[6]": "",
  "settings_custom_bookmark[7]": "#",
  "settings_bookmarks_title[43]": "Custom7",
  "settings_custom_bookmark_target[7]": "",
  "settings_custom_bookmark[8]": "#",
  "settings_bookmarks_title[44]": "Custom8",
  "settings_custom_bookmark_target[8]": "",
  "settings_custom_bookmark[9]": "#",
  "settings_bookmarks_title[45]": "Custom9",
  "settings_custom_bookmark_target[9]": "",
  "settings_bookmarks_title[0]": "",
  "settings_bookmarks_title[1]": "",
  "settings_bookmarks_title[2]": "",
  "settings_bookmarks_title[3]": "",
  "settings_bookmarks_title[4]": "",
  "settings_bookmarks_title[5]": "",
  "settings_bookmarks_title[6]": "",
  "settings_bookmarks_title[7]": "",
  "settings_bookmarks_title[8]": "",
  "settings_bookmarks_title[9]": "",
  "settings_bookmarks_title[10]": "",
  "settings_bookmarks_title[11]": "",
  "settings_bookmarks_title[12]": "",
  "settings_bookmarks_title[13]": "",
  "settings_bookmarks_title[14]": "",
  "settings_bookmarks_title[15]": "",
  "settings_bookmarks_title[16]": "",
  "settings_bookmarks_title[17]": "",
  "settings_bookmarks_title[18]": "",
  "settings_bookmarks_title[19]": "",
  "settings_bookmarks_title[20]": "",
  "settings_bookmarks_title[21]": "",
  "settings_bookmarks_title[22]": "",
  "settings_bookmarks_title[23]": "",
  "settings_bookmarks_title[24]": "",
  "settings_bookmarks_title[25]": "",
  "settings_bookmarks_title[26]": "",
  "settings_bookmarks_title[27]": "",
  "settings_bookmarks_title[28]": "",
  "settings_bookmarks_title[29]": "",
  "settings_bookmarks_title[30]": "",
  "settings_bookmarks_title[31]": "",
  "settings_bookmarks_title[32]": "",
  "settings_bookmarks_title[33]": "",
  "settings_bookmarks_title[34]": "",
  "settings_bookmarks_title[35]": "",
  "settings_bookmarks_title[46]": "",
  "settings_bookmarks_title[47]": "",
  "settings_bookmarks_title[48]": "",
  "settings_bookmarks_title[49]": "",
  "settings_bookmarks_title[50]": "",
  "settings_bookmarks_title[51]": "",
  "settings_bookmarks_title[52]": "",
  "settings_bookmarks_title[53]": "",
  "settings_bookmarks_title[54]": "",
  "settings_bookmarks_title[55]": "",
  "settings_bookmarks_title[56]": "",
  "settings_bookmarks_title[57]": "",
  "settings_bookmarks_title[58]": "",
  "settings_bookmarks_title[59]": "",
  "settings_bookmarks_title[60]": "",
  "settings_bookmarks_title[61]": "",
  "settings_bookmarks_title[62]": "",
  "settings_bookmarks_title[63]": "",
  "settings_bookmarks_title[64]": "",
  "settings_bookmarks_title[65]": "",
  "settings_bookmarks_title[66]": "",
  "settings_bookmarks_title[67]": "",
  "settings_bookmarks_title[68]": "",
  "settings_bookmarks_title[69]": "",
  "settings_bookmarks_title[70]": "",
  "settings_bookmarks_title[71]": "",
  "settings_bookmarks_title[72]": "",
  "settings_bookmarks_title[73]": "",
  "settings_bookmarks_title[74]": "",
  "settings_bookmarks_title[75]": "",
  "settings_bookmarks_title[76]": "",
  "settings_bookmarks_title[77]": "",
  "settings_bookmarks_title[78]": "",
  "settings_bookmarks_title[79]": "",
  "settings_bookmarks_title[80]": "",
  "settings_bookmarks_title[81]": "",
  "settings_bookmarks_title[82]": "",
  "settings_bookmarks_title[83]": "",
  "settings_bookmarks_title[84]": "",
  "settings_bookmarks_title[85]": "",
  "settings_bookmarks_title[86]": "",
  "settings_bookmarks_title[87]": "",
  "settings_bookmarks_title[88]": "",
  "settings_submit_log_button": true,
  "settings_log_inline": false,
  "settings_log_inline_tb": false,
  "settings_log_inline_pmo4basic": true,
  "settings_bookmarks_show": true,
  "settings_change_header_layout": true,
  "settings_fixed_header_layout": false,
  "settings_remove_logo": false,
  "settings_remove_message_in_header": false,
  "settings_bookmarks_on_top": true,
  "settings_bookmarks_top_menu": true,
  "settings_bookmarks_search": true,
  "settings_bookmarks_search_default": "",
  "settings_redirect_to_map": false,
  "settings_new_width": "1000",
  "settings_hide_facebook": true,
  "settings_hide_socialshare": true,
  "settings_hide_disclaimer": true,
  "settings_hide_cache_notes": false,
  "settings_adapt_height_cache_notes": true,
  "settings_hide_empty_cache_notes": true,
  "settings_show_all_logs": true,
  "settings_show_all_logs_count": "30",
  "settings_decrypt_hint": true,
  "settings_visitCount_geocheckerCom": true,
  "settings_show_bbcode": true,
  "settings_show_mail": true,
  "settings_font_size_menu": "16",
  "settings_font_size_submenu": "15",
  "settings_distance_menu": "16",
  "settings_distance_submenu": "8",
  "settings_font_color_menu_submenu": "93B516",
  "settings_font_color_menu": "93B516",
  "settings_font_color_submenu": "93B516",
  "settings_menu_number_of_lines": "1",
  "settings_menu_show_separator": false,
  "settings_menu_float_right": false,
  "settings_gc_tour_is_working": false,
  "settings_show_smaller_gc_link": true,
  "settings_show_message": true,
  "settings_show_remove_ignoring_link": true,
  "settings_use_one_click_ignoring": true,
  "settings_use_one_click_watching": true,
  "settings_show_common_lists_in_zebra": true,
  "settings_show_common_lists_color_user": true,
  "settings_show_cache_listings_in_zebra": false,
  "settings_show_cache_listings_color_user": true,
  "settings_show_cache_listings_color_owner": true,
  "settings_show_cache_listings_color_reviewer": true,
  "settings_show_cache_listings_color_vip": true,
  "settings_show_tb_listings_in_zebra": true,
  "settings_show_tb_listings_color_user": true,
  "settings_show_tb_listings_color_owner": true,
  "settings_show_tb_listings_color_reviewer": true,
  "settings_show_tb_listings_color_vip": true,
  "settings_lines_color_zebra": "EBECED",
  "settings_lines_color_user": "C2E0C3",
  "settings_lines_color_owner": "E0E0C3",
  "settings_lines_color_reviewer": "EAD0C3",
  "settings_lines_color_vip": "F0F0A0",
  "settings_show_mail_in_allmyvips": true,
  "settings_show_mail_in_viplist": true,
  "settings_process_vup": true,
  "settings_show_vup_friends": false,
  "settings_vup_hide_avatar": false,
  "settings_vup_hide_log": false,
  "settings_f2_save_gclh_config": true,
  "settings_esc_close_gclh_config": true,
  "settings_f4_call_gclh_config": true,
  "settings_f10_call_gclh_sync": true,
  "settings_show_sums_in_bookmark_lists": true,
  "settings_show_sums_in_watchlist": true,
  "settings_hide_warning_message": true,
  "settings_show_save_message": true,
  "settings_map_overview_build": true,
  "settings_map_overview_zoom": "11",
  "settings_map_overview_layer": "Geocaching",
  "settings_logit_for_basic_in_pmo": true,
  "settings_log_statistic": true,
  "settings_log_statistic_percentage": true,
  "settings_log_statistic_reload": "8",
  "settings_count_own_matrix": true,
  "settings_count_foreign_matrix": true,
  "settings_count_own_matrix_show_next": true,
  "settings_count_own_matrix_show_count_next": "2",
  "settings_count_own_matrix_show_color_next": "5151FB",
  "settings_count_own_matrix_links_radius": "25",
  "settings_count_own_matrix_links": "map",
  "settings_hide_left_sidebar_on_google_maps": true,
  "settings_add_link_gc_map_on_google_maps": true,
  "settings_switch_from_google_maps_to_gc_map_in_same_tab": false,
  "settings_add_link_new_gc_map_on_google_maps": true,
  "settings_switch_from_google_maps_to_new_gc_map_in_same_tab": false,
  "settings_add_link_google_maps_on_gc_map": true,
  "settings_switch_to_google_maps_in_same_tab": false,
  "settings_add_link_gc_map_on_osm": true,
  "settings_switch_from_osm_to_gc_map_in_same_tab": false,
  "settings_add_link_new_gc_map_on_osm": true,
  "settings_switch_from_osm_to_new_gc_map_in_same_tab": false,
  "settings_add_link_osm_on_gc_map": true,
  "settings_switch_to_osm_in_same_tab": false,
  "settings_add_link_flopps_on_gc_map": true,
  "settings_switch_to_flopps_in_same_tab": false,
  "settings_add_link_geohack_on_gc_map": true,
  "settings_switch_to_geohack_in_same_tab": false,
  "settings_sort_default_bookmarks": true,
  "settings_make_vip_lists_hideable": true,
  "settings_show_latest_logs_symbols": true,
  "settings_show_latest_logs_symbols_count": "10",
  "settings_set_default_langu": false,
  "settings_default_langu": "English",
  "settings_hide_colored_versions": false,
  "settings_make_config_main_areas_hideable": true,
  "settings_faster_profile_trackables": false,
  "settings_show_eventday": true,
  "settings_show_google_maps": true,
  "settings_show_log_it": true,
  "settings_show_nearestuser_profil_link": true,
  "settings_show_homezone": true,
  "settings_homezone_radius": "10",
  "settings_homezone_color": "0000FF",
  "settings_homezone_opacity": "10",
  "settings_multi_homezone": "{}",
  "settings_show_hillshadow": false,
  "settings_map_layers": "Geocaching###OpenStreetMap Default###OpenStreetMap German Style###OpenStreetMap Black and White###OpenStreetMap Hike and Bike###Thunderforest OpenCycleMap###Thunderforest Transport###Thunderforest Landscape###Stamen Toner###Stamen Terrain###Stamen Watercolor###Esri WorldStreetMap###Esri DeLorme###Esri WorldTopoMap###Esri WorldImagery###Esri OceanBasemap###Esri NatGeoWorldMap###Google Maps###Google Maps Satellite###Google Maps Hybrid",
  "settings_default_logtype": "-1",
  "settings_default_logtype_event": "-1",
  "settings_default_logtype_owner": "-1",
  "settings_default_tb_logtype": "-1",
  "settings_bookmarks_list": "[\"31\",\"69\",\"14\",\"16\",\"32\",\"33\",\"48\",\"0\",\"8\",\"18\",\"54\",\"51\",\"55\",\"47\",\"10\",\"2\",\"35\",\"9\",\"17\",\"22\",\"66\",\"68\"]",
  "settings_sync_last": "Thu Jan 01 1970 01:00:00 GMT+0100 (Mitteleuropäische Zeit)",
  "settings_sync_hash": "",
  "settings_sync_time": 36000000,
  "settings_sync_autoImport": false,
  "settings_hide_advert_link": true,
  "settings_hide_spoilerwarning": true,
  "settings_hide_hint": false,
  "settings_strike_archived": true,
  "settings_highlight_usercoords": true,
  "settings_highlight_usercoords_bb": false,
  "settings_highlight_usercoords_it": true,
  "settings_map_hide_found": true,
  "settings_map_hide_hidden": true,
  "settings_map_hide_dnfs": true,
  "settings_map_hide_2": false,
  "settings_map_hide_9": false,
  "settings_map_hide_5": false,
  "settings_map_hide_3": false,
  "settings_map_hide_6": false,
  "settings_map_hide_453": false,
  "settings_map_hide_7005": false,
  "settings_map_hide_13": false,
  "settings_map_hide_1304": false,
  "settings_map_hide_4": false,
  "settings_map_hide_11": false,
  "settings_map_hide_137": false,
  "settings_map_hide_8": false,
  "settings_map_hide_1858": false,
  "settings_show_fav_percentage": true,
  "settings_show_vip_list": true,
  "settings_show_owner_vip_list": true,
  "settings_autovisit": true,
  "settings_show_thumbnails": true,
  "settings_imgcaption_on_top": false,
  "settings_hide_avatar": false,
  "settings_link_big_listing": true,
  "settings_show_big_gallery": false,
  "settings_automatic_friend_reset": false,
  "settings_show_long_vip": false,
  "settings_load_logs_with_gclh": true,
  "settings_map_add_layer": true,
  "settings_map_default_layer": "OpenStreetMap Default",
  "settings_hide_map_header": false,
  "settings_spoiler_strings": "spoiler|hinweis",
  "settings_replace_log_by_last_log": false,
  "settings_hide_top_button": false,
  "settings_show_real_owner": false,
  "settings_hide_archived_in_owned": false,
  "settings_show_button_for_hide_archived": true,
  "settings_hide_visits_in_profile": false,
  "settings_log_signature_on_fieldnotes": true,
  "settings_map_hide_sidebar": true,
  "settings_hover_image_max_size": "600",
  "settings_vip_show_nofound": true,
  "settings_use_gclh_layercontrol": true,
  "settings_fixed_pq_header": true,
  "settings_friendlist_summary": true,
  "settings_friendlist_summary_viponly": false,
  "settings_search_data": "[]",
  "settings_search_enable_user_defined": true,
  "settings_pq_warning": true,
  "settings_pq_set_cachestotal": true,
  "settings_pq_cachestotal": "1000",
  "settings_pq_option_ihaventfound": true,
  "settings_pq_option_idontown": true,
  "settings_pq_option_ignorelist": true,
  "settings_pq_option_isenabled": true,
  "settings_pq_option_filename": true,
  "settings_pq_set_terrain": true,
  "settings_pq_set_difficulty": true,
  "settings_pq_difficulty": ">=",
  "settings_pq_difficulty_score": "1",
  "settings_pq_terrain": ">=",
  "settings_pq_terrain_score": "1",
  "settings_pq_automatically_day": false,
  "settings_pq_previewmap": true,
  "settings_pq_previewmap_layer": "Geocaching",
  "settings_mail_icon_new_win": false,
  "settings_message_icon_new_win": false,
  "settings_hide_cache_approvals": true,
  "settings_driving_direction_link": true,
  "settings_driving_direction_parking_area": false,
  "settings_show_elevation_of_waypoints": true,
  "settings_primary_elevation_service": "3",
  "settings_secondary_elevation_service": "2",
  "settings_distance_units": "Metric",
  "settings_img_warning": false,
  "settings_fieldnotes_old_fashioned": false,
  "settings_remove_banner": false,
  "settings_remove_banner_for_garminexpress": false,
  "settings_remove_banner_blue": false,
  "settings_compact_layout_bm_lists": true,
  "settings_compact_layout_pqs": true,
  "settings_compact_layout_list_of_pqs": true,
  "settings_compact_layout_nearest": true,
  "settings_compact_layout_recviewed": true,
  "settings_map_links_statistic": true,
  "settings_map_percentage_statistic": true,
  "settings_improve_add_to_list_height": "205",
  "settings_improve_add_to_list": true,
  "remove_navi_play": false,
  "remove_navi_community": false,
  "remove_navi_shop": false,
  "settings_show_flopps_link": true,
  "settings_show_brouter_link": true,
  "settings_show_gpsvisualizer_link": true,
  "settings_show_gpsvisualizer_gcsymbols": true,
  "settings_show_gpsvisualizer_typedesc": true,
  "settings_show_openrouteservice_link": true,
  "settings_show_openrouteservice_home": false,
  "settings_show_openrouteservice_medium": "2b",
  "settings_show_copydata_menu": true,
  "settings_show_default_links": true,
  "settings_bm_changed_and_go": true,
  "settings_bml_changed_and_go": true,
  "settings_show_tb_inv": true,
  "settings_but_search_map": true,
  "settings_but_search_map_new_tab": false,
  "settings_show_pseudo_as_owner": true,
  "settings_fav_proz_pqs": true,
  "settings_fav_proz_nearest": true,
  "settings_fav_proz_recviewed": true,
  "settings_show_all_logs_but": true,
  "settings_show_log_counter_but": true,
  "settings_show_log_counter": false,
  "settings_show_bigger_avatars_but": true,
  "settings_hide_feedback_icon": false,
  "settings_compact_layout_new_dashboard": false,
  "settings_show_draft_indicator": true,
  "settings_show_enhanced_map_popup": true,
  "settings_show_enhanced_map_coords": true,
  "settings_show_latest_logs_symbols_count_map": "16",
  "settings_modify_new_drafts_page": true,
  "settings_gclherror_alert": false,
  "settings_auto_open_tb_inventory_list": true,
  "settings_embedded_smartlink_ignorelist": true,
  "settings_both_tabs_list_of_pqs_one_page": false,
  "settings_past_events_on_bm": true,
  "settings_show_log_totals": true,
  "settings_show_reviewer_as_vip": true,
  "settings_hide_found_count": false,
  "settings_show_compact_logbook_but": true,
  "settings_log_status_icon_visible": true,
  "settings_cache_type_icon_visible": true,
  "settings_showUnpublishedHides": true,
  "settings_set_showUnpublishedHides_sort": true,
  "settings_showUnpublishedHides_sort": "abc",
  "settings_lists_compact_layout": false,
  "settings_lists_disabled": false,
  "settings_lists_disabled_color": "4A4A4A",
  "settings_lists_disabled_strikethrough": true,
  "settings_lists_archived": false,
  "settings_lists_archived_color": "8C0B0B",
  "settings_lists_archived_strikethrough": true,
  "settings_lists_icons_visible": false,
  "settings_lists_log_status_icons_visible": true,
  "settings_lists_cache_type_icons_visible": true,
  "settings_lists_premium_column": false,
  "settings_lists_found_column_bml": false,
  "settings_lists_show_log_it": false,
  "settings_lists_back_to_top": false,
  "settings_searchmap_autoupdate_after_dragging": true,
  "settings_improve_character_counter": true,
  "settings_searchmap_compact_layout": true,
  "settings_searchmap_disabled": false,
  "settings_searchmap_disabled_strikethrough": true,
  "settings_searchmap_disabled_color": "4A4A4A",
  "settings_searchmap_show_hint": false,
  "settings_show_copydata_own_stuff_show": false,
  "settings_show_copydata_own_stuff_name": "Photo file name",
  "settings_show_copydata_own_stuff_value": "#yyyy#.#mm#.#dd# - #GCName# - #GCCode# - 01",
  "settings_show_copydata_own_stuff": "{}",
  "settings_relocate_other_map_buttons": true,
  "settings_show_radius_on_flopps": true,
  "settings_show_edit_links_for_logs": true,
  "settings_show_copydata_plus": false,
  "settings_show_copydata_separator": "‌‌‌‌‌‌‌‌‌\n",
  "settings_mail_signature": "",
  "friends_founds_last": "0",
  "vips": false,
  "friends_founds_last_reset": 1614754678512,
  "vups": false,
  "uid": "b978708c-e59f-4ed9-8b38-91c60f19ee0e",
  "show_box_gclh_vip_list": true,
  "show_box_gclh_vip_list_nofound": true,
  "settings_log_template_name[0]": "",
  "settings_log_template_name[1]": "",
  "settings_log_template_name[2]": "",
  "settings_log_template_name[3]": "",
  "settings_log_template_name[4]": "",
  "settings_log_template_name[5]": "",
  "settings_log_template_name[6]": "",
  "settings_log_template_name[7]": "",
  "settings_log_template_name[8]": "",
  "settings_log_template_name[9]": "",
  "last_logtext": "",
  "show_box_dashboard_linklist": true,
  "show_box_dashboard_links": true,
  "show_box_dashboard_vip": true,
  "show_box_dashboard_vup": true,
  "show_box_dashboard_1": true,
  "show_box_dashboard_2": true,
  "show_box_dashboard_3": true,
  "show_box_dashboard_4": true,
  "show_box_dashboard_5": true,
  "show_box_dashboard_6": true,
  "unpublishedCaches_visible": false,
  "show_box_nearby_events": true,
  "settings_log_template[0]": "",
  "settings_log_template[1]": "",
  "settings_log_template[2]": "",
  "settings_log_template[3]": "",
  "settings_log_template[4]": "",
  "settings_log_template[5]": "",
  "settings_log_template[6]": "",
  "settings_log_template[7]": "",
  "settings_log_template[8]": "",
  "settings_log_template[9]": "",
  "settings_log_signature": "",
  "settings_tb_signature": "",
  "show_box_gclh_config_global": true,
  "show_box_gclh_config_config": true,
  "show_box_gclh_config_nearestlist": true,
  "show_box_gclh_config_pq": true,
  "show_box_gclh_config_bm": true,
  "show_box_gclh_config_recview": true,
  "show_box_gclh_config_friends": true,
  "show_box_gclh_config_hide": true,
  "show_box_gclh_config_others": true,
  "show_box_gclh_config_maps": true,
  "show_box_gclh_config_profile": true,
  "show_box_gclh_config_db": true,
  "show_box_gclh_config_listing": true,
  "show_box_gclh_config_logging": true,
  "show_box_gclh_config_mail": true,
  "show_box_gclh_config_linklist": true,
  "show_box_gclh_config_development": true,
  "migration_task_02": true,
  "show_box_searchmap_activity": true,
  "email_sendaddress": "checked",
  "email_mailcopy": false,
  "settings_lists_show_dd": true,
  "settings_lists_hide_desc": true,
  "settings_lists_upload_file": true,
  "migration_task_03": true,
  "gclhLeafletMapActive": true
}
```

**Comment by 2Abendsegler** [comment]
@capoaira 
Brauch mal Hilfe. 

Habe mit der Config getestet auf FF und Chrome. Ich kann den Fehler nicht nachstellen.

Ich habe mir nochmal die Konsole Fehlermeldungen angesehen.
Ganz unten steht noch folgendes:
```
userscript.html?name=GC%20little%20helper%20II.user.js&id=c652b406-d4ab-405e-805a-92fdc4933dde:10861 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
at MutationObserver.cb_sidebar (userscript.html?name=GC%20little%20helper%20II.user.js&id=c652b406-d4ab-405e-805a-92fdc4933dde:10861) 
```

Das relevante Coding im GClh:
```
            // Observer callback for sidebar.
            var cb_sidebar = function(mutationsList, observer) {
                observer_sidebar.disconnect();
                processAllSearchMap();
                var target_sidebar = $('div#sidebar')[0];
                var config_sidebar = {
                    childList: true,
                    subtree: true
                };
                observer_sidebar.observe(target_sidebar, config_sidebar);
            }
```

Könnte das bedeuten dass $('div#sidebar')[0] nicht vorhanden ist?

**Comment by capoaira** [comment]
Ja, das denke ich auch. Aber beim erstem mal wird abgefragt, deswegen ist das Element zwischenzeitlich vorhanden.

**Comment by 2Abendsegler** [comment]
[Im Forum veröffentlicht](https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/&do=findComment&comment=5877568):

@mr.checkmate

Du hast uns ja deine Einstellungen zum GClh zukommen lassen. Leider komme ich damit auch nicht weiter. Wir können also das Problem weiterhin nicht nachvollziehen.


Die Fehlermeldungen aus der Konsole - sind glaube ich auch von dir - legen nahe, dass die Sidebar auf der Karte links nicht mehr vorhanden ist. Denn der GClh hat ebenfalls ein Problem in der Konsole ausgegeben.

Frage 1: Kannst du bestätigen, dass die Sidebar auch fehlt, wenn die Karte weiß ist?


Frage 2: Bleibt der Karteninhalt bei dir immer weiß, oder nur gelegentlich?


Frage3: Könntest du mir bitte im Fehlerfall übers Message Center eine Bildschirmkopie deines Browsers zuschicken. Es sollte der ganze Browser sichtbar sein, also auch das Menü und die Browsericons. Vielleicht fällt uns dann noch etwas ein. Im Moment sind wir nämlich ratlos.

**Comment by 2Abendsegler** [comment]
> Frage 1: Kannst du bestätigen, dass die Sidebar auch fehlt, wenn die Karte weiß ist?
> 
> Frage 2: Bleibt der Karteninhalt bei dir immer weiß, oder nur gelegentlich?
> 
> Frage3: Könntest du mir bitte im Fehlerfall übers Message Center eine Bildschirmkopie deines Browsers zuschicken. Es sollte der ganze Browser sichtbar sein, also auch das Menü und die Browsericons. Vielleicht fällt uns dann noch etwas ein. Im Moment sind wir nämlich ratlos.

Antworten über Message Center erhalten.
Zu 1: Die Sidebar ist auch weg. Der Karteninhalt ist komplett weiß.
Zu 2: Manchmal ist der Karteninhalt sofort nach dem Laden der Seite weiß, manchmal erst sobald man die Karte verschiebt oder scrollt. Aber spätestens nach der ersten Aktion auf der Karte wird sie weiß.
Zu3: Hat keine Erkenntnisse gebracht.

Das Problem ist nicht nachvollziehbar.

**Comment by capoaira** [comment]
Tatsächlich konnte ich den Bug heute einige Male nachstellen, sobald ich einen Filter (in meinem Fall das Attribut Nachtcache) gesetzt habe:
![grafik](https://user-images.githubusercontent.com/50927164/114310902-ce5b9580-9aec-11eb-8b9a-dfa1952a3dd2.png)
Allerdings tritt der Bug nicht nachvollziehbar auf. Mal kann ich die Karte noch ein paar wenige Male bewegen, mal etwas häufiger.
Dabei habe ich im Inspektor rausgefunden, dass der komplette `div#root` leer ist. Scheinbar überschneiden sich die Skripte von GS uns unseres so, dass das Skript von GS abbricht. Hier den Fehler zu finden wird sicherlich schwer oder sogar unmöglich.
Ich kann mich die nächste Zeit aber nicht damit beschäftigen, da ich bald meine Abi Prüfungen schreibe.

**Comment by 2Abendsegler** [comment]
Konnte das wie folgt nachstellen:
- Neue Karte aufrufen.
- Filter klicken.
- Nur den Cache Typ Event wählen.
- Done klicken.
- Mit Maus über der Karte herauszomen und schnell auf Search this area klicken.

**Comment by 2Abendsegler** [comment]
[Info und Bitte zum Testen an User im geoclub gegeben.](https://forums.geocaching.com/GC/index.php?/topic/343005-gc-little-helper-ii/&do=findComment&comment=5884915)

**Comment by 2Abendsegler** [comment]
merged
